apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      resourceLock: leases
      resourceName: edge-scheduler
      resourceNamespace: kube-system
      retryPeriod: 2s
    percentageOfNodesToScore: 0
    podInitialBackoffSeconds: 1
    podMaxBackoffSeconds: 10
    profiles:
      - schedulerName: edge-scheduler
        plugins:
          queueSort:
            enabled:
              - name: delaysensitive
          score:
            enabled:
              - name: computeintensive
                weight: 1
            enabled:
              - name: dataintensive
                weight: 1
            enabled:
              - name: delaysensitive
                weight: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-scheduler
  namespace: kube-system
  labels:
    component: edge-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: edge-scheduler
  template:
    metadata:
      labels:
        component: edge-scheduler
    spec:
      serviceAccount: edge-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: edge-scheduler
          image: registry.cn-guangzhou.aliyuncs.com/yunmengze/edge-scheduler:0.01
          imagePullPolicy: IfNotPresent
          args:
            - edge-scheduler
            - --config=/scheduler/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "300m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /scheduler